---

- name: installer le serveur
  hosts: all
  remote_user: ansadmin
  become: true
  tasks:
    - include_vars:
        file: vars.yml
    - include_role: 
        name: setup 
    - include_role:
        name: packages
    - include_role:
        name: firewall
    - include_role:
        name: php


