# ============================================================
# Inventaire Ansible — StockMaster
# Remplacer les <IP_Mx> par les vraies adresses IP EC2
# Pour mono-machine : mettre la même IP partout
# ============================================================

[db]
db1 ansible_host=<IP_DB> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/bechir.pem

[backend]
back1 ansible_host=<IP_BACK1> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/bechir.pem
back2 ansible_host=<IP_BACK2> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/bechir.pem

[frontend]
front1 ansible_host=<IP_FRONT> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/bechir.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
