---
- name: Install apache  web server packages
  apt:
    name: apache2
    state: present

- name: Copy configuration file
  template:
    src: templates/httpd.conf.j2
    dest: /etc/apache2/httpd.conf

- name: Restart web server
  service:
    name: apache2
    state: restarted

