- name: deploy project
  hosts: all
  remote_user: ansadmin
  become: true
  tasks:
    - include_vars:
        file: vars.yml
    - include_vars:
        file: secrets.yml
          #- include_role:
          # name: ansistrano.deploy
    - include_role:
        name: backup




