---
# Install nginx and python
- name: Install packages
  hosts: all
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - python3
