apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: flotte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          volumeMounts:
            - name: cfg
              mountPath: /etc/prometheus
      volumes:
        - name: cfg
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml

