---
- name: Example de playbook où la varaible est définie au niveau de la tâche
  hosts: ubuntu
  tasks:
  - name: varaible au niveau de la tâche
    set_fact:
      valeur: "Hello, world!"

  - name: Display the task-level variable
    debug:
      msg: "{{ valeur }}"
