---
# tasks file for php
- name: add andrej/php repo 
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Disable php errors 
  lineinfile:
    dest: "etc/php{{php_version}}/fpm/php.ini"
    regexp: "display_errors="
    line: "display_errors=0"
  ignore_errors: true
  notify: PHP Restart  

- name: Install php
  apt:
    update_cache: true
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
    state: present

- name: Install Composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"

- name: Post Install Composer
  shell:
    mv composer.phar /usr/local/bin/composer
  args: 
    creates: /usr/local/bin/composer 


