spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  jwt:
    secret: stockmaster-secret-key-must-be-at-least-256-bits-long-for-hs256
    expiration: 86400000
