spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stockmaster
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
