---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: mysql-app
type: Opaque
stringData:
  # Format: username:password@(hostname:port)/
  DATA_SOURCE_NAME: "appuser:AppU5er@2024@(mysql-service:3306)/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: mysql-app
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.15.0
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: DATA_SOURCE_NAME
        ports:
        - containerPort: 9104
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: mysql-app
  labels:
    app: mysql-exporter
spec:
  ports:
  - port: 9104
    targetPort: 9104
    name: metrics
  selector:
    app: mysql-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: mysql-app
  labels:
    app: mysql-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
  - port: metrics
    interval: 30s
