apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Utilise un Network Load Balancer (idéal pour MySQL)
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306          # Port exposé par le service
      targetPort: 3306    # Port sur lequel MySQL fonctionne dans le pod
  type: LoadBalancer

