apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.14.0
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "root:rootpassword@(mysql-service.default.svc.cluster.local:3306)/"
            - name: EXPORTER_FLAGS
              value: "--collect.slave_status=false"

