apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape configuration for Kubernetes pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app]
            regex: mysql

      # Scrape configuration for mysqld_exporter
      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['mysql-exporter.monitoring.svc.cluster.local:9104']

