apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: test123++
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d
