- name: Mettre à jour la liste des paquets
  apt:
    update_cache: yes

- name: Installer les dépendances
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present

- name: Ajouter la clé GPG officielle Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le repository Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Installer Docker
  apt:
    name: docker-ce
    state: present

- name: Activer et démarrer Docker
  systemd:
    name: docker
    enabled: yes
    state: started

